# The Site Configuration
theme: jekyll-theme-chirpy

lang: zh-TW
timezone: Asia/Taipei

title: Squiz Today 學習筆記
tagline: 每日 Squiz Today 英文學習筆記
description: >-
  每日 Squiz Today 英文學習筆記（News Highlights、進階單字、Aussie slang、逐字稿）

url: "https://chchwy.github.io"
baseurl: "/squiz-note"

github:
  username: chchwy

social:
  name: chchwy
  links:
    - https://github.com/chchwy/squiz-note

# Theme Mode: [light | dark | (empty for system preference with toggle)]
theme_mode:

paginate: 10

# Table of Contents
toc: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
